export const GET_CATEGORIRES_REQUEST = "GET_CATEGORIRES_REQUEST";
export const SAVE_ATTRIBUTES = 'SAVE_ATTRIBUTES'
export const NEW_CATEGORY = 'NEW_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'