export const HEADS_BUBBLES = "HEADS_BUBBLES";
export const SET_ADMIN_SOCKET = "SET_ADMIN_SOCKET";
export const ADMIN_MESSAGE_NOTIFICATION = "ADMIN_MESSAGE_NOTIFICATION";
export const INACTIVE_HEADS_BUBBLES = "INACTIVE_HEADS_BUBBLES";
