const ProductSeeder = [
  {
    name: "Laptop DELL G15 5525-8403 15.6 cali R5-6600H 16GB RAM 512GB SSD GeForce RTX3050 Windows 11 Home",
    description:
      "Jeśli szukasz laptopa, który utrzyma wysokie tempo pracy i rozrywki, postaw na G15 Ryzen Edition. Potężny procesor AMD Ryzen 7 6800H z łatwością sprosta wszystkim postawionym przed nim zadaniom, zarówno w pracy zawodowej czy nauce zdalnej, jak i w czasie wolnym. Szczególnie, gdy jesteś fanem gamingu. Pojemność wbudowanego dysku SSD sięga 512 GB. Wielkość pamięci RAM wynosi 16 GB.",
    count: 5,
    price: 100,
    category: "Komputery/Laptopy/Dell",
    images: [
      { path: "/img/front/lap1.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attributes: [
      { key: "RAM", value: "16 GB" },
      { key: "Dysk SSD", value: "250 GB" },
      { key: "Dysk HDD", value: "1 TB" },
      { key: "Karta graficzna", value: "NVIDIA GeForce RTX 3060 Ti" },
      { key: "Procesor", value: "Intel Core i5-11400F" },
      { key: "System operacyjny", value: "Windows" },
    ],
  },
  {
    name: "Laptop DELL Inspiron 3525-5431 15.6 cali R5-5500U 8GB RAM 512GB SSD Windows 11 Home",
    description:
      "Smukła obudowa inspirowana naturą i materiały z recyklingu sprawiają, że Inspiron 15 nie tylko wygląda wyjątkowo, ale jest także przyjazny środowisku. Doskonałe wrażenia wizualne zapewnia ekran z funkcją Dell Comfort View, a niezawodność działania procesor AMD Ryzen 5 5500U. To dobry wybór zarówno do pracy, jak i do nauki.",
    count: 5,
    price: 100,
    category: "Komputery/Laptopy/Dell",
    images: [
      { path: "/img/front/lap2.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attributes: [
      { key: "RAM", value: "8 GB" },
      { key: "Dysk SSD", value: "128 GB" },
      { key: "Dysk HDD", value: "1 TB" },
      { key: "Karta graficzna", value: "Intel Arc A750" },
      { key: "Procesor", value: "Intel Core i5-13400F" },
      { key: "System operacyjny", value: "Brak" },
    ],
  },
  {
    name: "Laptop ACER Nitro 5 AN515-57 15.6 cali IPS 144Hz i7-11800H 16GB RAM 1TB SSD GeForce RTX3070 Windows 11 Home",
    description:
      "Laptop ACER Nitro 5 dzięki połączonej mocy procesora Intel Core 11-stej generacji i układu graficznego NVIDIA GeForce RTX zawładniesz światem gier. Możliwość rozbudowy pamięci RAM DDR4 gwarantują maksymalną szybkość i ogromną ilość miejsca.",
    count: 5,
    price: 100,
    category: "Komputery/Laptopy/Acer",
    images: [
      { path: "/img/front/lap3.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attributes: [
      { key: "RAM", value: "32 GB" },
      { key: "Dysk SSD", value: "128 GB" },
      { key: "Dysk HDD", value: "1 TB" },
      { key: "Karta graficzna", value: "Intel Arc A750" },
      { key: "Procesor", value: "Intel Core i5-13400F" },
      { key: "System operacyjny", value: "Brak" },
    ],
  },
  {
    name: "Tablet SAMSUNG Galaxy Tab A8 10.5 cali 4/64 GB Wi-Fi Szary",
    description:
      "Tablet SAMSUNG Galaxy Tab A8 to wyjątkowo wszechstronny model o wspaniałych parametrach. Nowoczesny i wydajny procesor oraz pamięć RAM 4 GB i duża pamięć wbudowana umożliwiają stworzenie ogromnej bazy aplikacji lub plików, która będzie zawsze pod ręką. Wbudowany mikrofon i głośniki, technologia Bluetooth i Wi-Fi oraz system operacyjny Android 11 zapewniają szerokie możliwości wykorzystania tabletu. Co więcej, tablet jest wytrzymały i wygodny w obsłudze.",
    count: 5,
    price: 100,
    category: "Tablety",
    images: [
      { path: "/img/front/t4.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attributes: [
      { key: "Wyświetlacz", value: "10.5 cali, 1920 x 1200px, TFT" },
      { key: "Kolor", value: "grafitowy" },
      { key: "Funkcje ekranu", value: "Dotykowy" },
      { key: "Pamięć wbudowana", value: "64 GB" },
      { key: "RAM", value: "4 GB" },
      { key: "Procesor", value: "UNISOC T618, 8-rdzeniowy" },
      { key: "Pojemność akumulatora", value: "7040 mAh" },
      { key: "System operacyjny", value: "Android 11" },
      { key: "Złącza", value: "Złącze USB" },
    ],
  },
  {
    name: "Tablet APPLE iPad 10.2 cali 9 gen. 256GB Wi-Fi Gwiezdna szarość",
    description:
      "Praca, zabawa, kreacja, nauka, komunikacja i mnóstwo innych rzeczy. Bo APPLE iPad jest mocny. Przyjazny. Wszechstronny. I zadziwiająco przystępny.",
    count: 10,
    price: 200,
    category: "Tablety",
    images: [
      { path: "/img/front/t1.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
    attributes: [
      { key: "Wyświetlacz", value: "10.2 cali, 2160 x 1620px, Retina" },
      { key: "Kolor", value: "gwiezdna szarość" },
      { key: "Funkcje ekranu", value: "Dotykowy" },
      { key: "Pamięć wbudowana", value: "256 GB" },
      { key: "RAM", value: "4 GB" },
      { key: "Procesor", value: "Apple A13 Bionic" },
      { key: "Pojemność akumulatora", value: "7040 mAh" },
      { key: "System operacyjny", value: "iPadOS 15" },
      { key: "Złącza", value: "Złącze USB" },
    ],
  },
  {
    name: "Tablet LENOVO Tab M10 3 gen. TB328XU 10.1 cali 3/32 GB LTE Wi-Fi Szary",
    description:
      "Tablet firmy Lenovo w kolorze szarym z procesorem UNISOC T610 oraz układem graficznym ARM Mali-G52 3EE, posiada wbudowany aparat przedni 5.0 Mpix oraz tylny 8.0 Mpix. Zainstalowany system operacyjny to Android 11. Pamięć RAM wynosi 3 GB, pamięć wbudowana 32 GB.",
    count: 15,
    price: 300,
    category: "Tablety",
    images: [
      { path: "/img/front/t2.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 4,
    reviewsNumber: 7,
    reviews: [],
    attributes: [
      { key: "Wyświetlacz", value: "10.61 cala, 2000 x 1200px, IPS" },
      { key: "Kolor", value: "szary" },
      { key: "Funkcje ekranu", value: "Dotykowy" },
      { key: "Pamięć wbudowana", value: "32 GB" },
      { key: "RAM", value: "3 GB" },
      { key: "Procesor", value: "UNISOC T618, 8-rdzeniowy" },
      { key: "Pojemność akumulatora", value: "7040 mAh" },
      { key: "System operacyjny", value: "Android 12" },
      { key: "Złącza", value: "Złącze USB" },
    ],
  },
  {
    name: "Tablet HUAWEI MatePad 11.5 cali 8/128 GB Wi-Fi Szary",
    description:
      "HUAWEI MatePad 11.5 cali zaprojektowano z myślą o osobach poszukujących do swojego mobilnego centrum dowodzenia tabletu, na którym mogą pracować lub uczyć się równie wygodnie i efektywnie jak na laptopie. Tablet wyposażono w duży ekran 11,5” o wysokiej rozdzielczości 2.2K z częstotliwością odświeżania do 120 Hz, co gwarantuje, że wyświetlany obraz będzie niezwykle wyraźny, żywy i płynny. To bardzo wszechstronne urządzenie do pracy zdalnej – wystarczy, że połączysz z nim klawiaturę, a zamieni się w lekki i poręczny notebook.",
    count: 20,
    price: 400,
    category: "Tablety",
    images: [
      { path: "/img/front/t3.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
    attributes: [
      { key: "Wyświetlacz", value: "10.61 cala, 2000 x 1200px, IPS" },
      { key: "Kolor", value: "szary" },
      { key: "Funkcje ekranu", value: "Dotykowy" },
      { key: "Pamięć wbudowana", value: "128 GB" },
      { key: "RAM", value: "8 GB" },
      { key: "Procesor", value: "UNISOC T618, 8-rdzeniowy" },
      { key: "Pojemność akumulatora", value: "7040 mAh" },
      { key: "System operacyjny", value: "Android 12" },
      { key: "Złącza", value: "Złącze słuchawkowe" },
    ],
  },
  {
    name: "Tablet LENOVO Tab P11 2 gen. TB350FU 11.5 cali 6/128 GB Wi-Fi Szary",
    description:
      "Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.",
    count: 25,
    price: 500,
    category: "Tablety",
    images: [
      { path: "/img/front/t4.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
    attributes: [
      { key: "Wyświetlacz", value: "10.61 cala, 2000 x 1200px, IPS" },
      { key: "Kolor", value: "szary" },
      { key: "Funkcje ekranu", value: "Dotykowy" },
      { key: "Pamięć wbudowana", value: "128 GB" },
      { key: "RAM", value: "6 GB" },
      { key: "Procesor", value: "UNISOC T618, 8-rdzeniowy" },
      { key: "Pojemność akumulatora", value: "7040 mAh" },
      { key: "System operacyjny", value: "Android 12" },
      { key: "Złącza", value: "Złącze USB" },
    ],
  },
  {
    name: "Monitor ACER Predator XB253QGW 24.5 cali 1920x1080px IPS 280Hz 1 ms",
    description:
      "Zobacz wyraźny obraz i rzeczywiste kolory na 25-calowym wyświetlaczu Full HD IPS. Ekran może służyć szerszej publiczności, ponieważ cienie i kontrast nie tracą jakości nawet przy kącie patrzenia równym 178°.",
    count: 5,
    price: 100,
    category: "Monitory",
    images: [
      { path: "/img/front/m1.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attributes: [
      { key: "Ekran", value: "24.5 cala, 1920 x 1080px, IPS" },
      { key: "Częstotliwość odświeżania obrazu", value: "280 Hz" },
      { key: "Czas reakcji matrycy", value: "1 ms" },
      { key: "Złącza", value: "HDMI" },
    ],
  },
  {
    name: "Monitor SAMSUNG Odyssey G5 LS27AG550EP 26.9 cali 2560x1440px 165Hz 1 ms Curved",
    description:
      "Twój świat gier, teraz zdumiewająco realistyczny. Dzięki gęstości pikseli 1,7 razy większej niż Full HD rozdzielczość WQHD zapewnia niewiarygodnie szczegółowy, ostry obraz. Doświadcz pełniejszego widoku z większą ilością miejsca na całą akcję. Gotowy do pokonania wrogów, opóźnień i rozmycia. Ultraszybka częstotliwość odświeżania 165 Hz obsługuje nawet najbardziej ekscytujące sceny i superszybkie efekty wizualne. Niech każdy ruch się liczy dzięki czasowi reakcji 1 ms. Skacz na wrogów, gdy tylko ich zobaczysz i trzymaj się z przodu dzięki precyzyjnym ruchom myszy. Twoja wydajność na ekranie jest tak szybka, jak Twój własny refleks.",
    count: 10,
    price: 200,
    category: "Monitory",
    images: [
      { path: "/img/front/m2.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
    attributes: [
      { key: "Ekran", value: "27 cala, 2560 x 1440px, IPS" },
      { key: "Częstotliwość odświeżania obrazu", value: "165 Hz" },
      { key: "Czas reakcji matrycy", value: "1 ms" },
      { key: "Złącza", value: "Wyjście słuchawkowe" },
    ],
  },
  {
    name: "Monitor ASUS TUF Gaming VG249QM1A 23.8 cali 1920x1080px IPS 270Hz 1 ms",
    description:
      "Monitor ASUS Tuf Gaming VG279QL1A ma ekran o przekątnej 24 cali i rozdzielczości 1920 x 1080 px z matrycą IPS. Częstotliwość odświeżania obrazu to 270 Hz, a czas reakcji matrycy - 1 ms. Jasność ekranu to 350 cd/m2, a proporcje - 16:9.",
    count: 15,
    price: 300,
    category: "Monitory",
    images: [
      { path: "/img/front/m3.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 4,
    reviewsNumber: 7,
    reviews: [],
    attributes: [
      { key: "Ekran", value: "27 cala, 1920 x 1080px, IPS" },
      { key: "Częstotliwość odświeżania obrazu", value: "280 Hz" },
      { key: "Czas reakcji matrycy", value: "1 ms" },
      { key: "Złącza", value: "DisplayPort" },
    ],
  },
  {
    name: "Monitor ACER Nitro QG270S3BIPX 27 cali 1920x1080px 180Hz 1ms",
    description:
      "Monitor ACER Nitro QG270S3BIPX oferuje niezwykle krótki czas reakcji, dzięki czemu każda akcja jest wyświetlana bez rozmycia czy smużenia. Dzięki trybowi Visual Response Boost i czasowi reakcji na poziomie 1 ms obraz jest wyraźny i nierozmywający się nawet w najbardziej dynamicznych scenach.",
    count: 20,
    price: 400,
    category: "Monitory",
    images: [
      { path: "/img/front/m4.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
    attributes: [
      { key: "Ekran", value: "24.5 cala, 1920 x 1080px, IPS" },
      { key: "Częstotliwość odświeżania obrazu", value: "144 Hz" },
      { key: "Czas reakcji matrycy", value: "1 ms" },
      { key: "Złącza", value: "Wyjście słuchawkowe " },
    ],
  },
  {
    name: "Monitor ASUS TUF Gaming VG249Q1A 23.8 cali 1920x1080px IPS 165Hz 1 ms",
    description:
      "TUF Gaming VG249Q1A to 23,8-calowy monitor z matrycą IPS o rozdzielczości Full HD (1920 x 1080) z ultraszybką częstotliwością odświeżania 165 Hz. Został on zaprojektowany dla graczy i innych użytkowników poszukujących immersyjnej rozgrywki i oferuje specyfikacje na wysokim poziomie.",
    count: 25,
    price: 500,
    category: "Monitory",
    images: [
      { path: "/img/front/m5.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
    attributes: [
      { key: "Ekran", value: "23.8 cala, 1920 x 1080px, IPS" },
      { key: "Częstotliwość odświeżania obrazu", value: "165 Hz" },
      { key: "Czas reakcji matrycy", value: "1 ms" },
      { key: "Złącza", value: "DisplayPort " },
    ],
  },
  {
    name: "Monitor IIYAMA G-Master GB3467WQSU-B5 34 cali 3440x1440px 165Hz 0.4 ms Curved",
    description:
      "Monitor IIYAMA G-Master GB3467WQSU-B5 gwarantuje ostry, płynny obraz pełen detali i głębokich kolorów. To zasługa zarówno wysokiej rozdzielczości 3440x1440 px, jak również zakrzywionej matrycy i szerokiego kąta widzenia. Funkcja Black Tuner pozwala na regulację jasnych oraz ciemnych tonów, co wpływa na jakość obrazu w zaciemnionych obszarach, z kolei przekątna wynosząca 34 cale pozwala poczuć się jak na sali kinowej. Ustawienia ekranu możesz z łatwością regulować przy użyciu niestandardowych i predefiniowanych trybów gier.",
    count: 5,
    price: 100,
    category: "Monitory",
    images: [
      { path: "/img/front/m6.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attributes: [
      { key: "Ekran", value: "23.8 cala, 1920 x 1080px, IPS" },
      { key: "Częstotliwość odświeżania obrazu", value: "165 Hz" },
      { key: "Czas reakcji matrycy", value: "1 ms" },
      { key: "Złącza", value: "HDMI" },
    ],
  },
  {
    name: "Marvel's Spider-Man 2 - Edycja Kolekcjonerska Gra PS5",
    description:
      "Gatunek: Akcja, Przygodowa",
    count: 10,
    price: 200,
    category: "Gry",
    images: [
      { path: "/img/front/gra1.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
    attributes: [
      { key: "Rodzaj gry", value: "Przygodowe" },
      { key: "Platforma", value: "PlayStation 5" },
    ],
  },
  {
    name: "Uncharted: Kolekcja Dziedzictwo Złodziei Gra PS5",
    description:
      "Gatunek: Akcja, Przygodowa Nośnik: Blu-ray Wersja językowa: Polska (dubbing) Platforma: PlayStation 5 Rodzaj: Gra",
    count: 15,
    price: 300,
    category: "Gry",
    images: [
      { path: "/img/front/gra2.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 4,
    reviewsNumber: 7,
    reviews: [],
    attributes: [
      { key: "Rodzaj gry", value: "Przygodowe" },
      { key: "Platforma", value: "PlayStation 5" },
    ],
  },
  {
    name: "EA SPORTS FC 24 Gra PC",
    description:
      "Gatunek: Sportowa Nośnik: Klucz aktywacyjny w pudełku Wersja językowa: Polska (dubbing) Platforma: PC Rodzaj: Gra",
    count: 20,
    price: 400,
    category: "Gry",
    images: [
      { path: "/img/front/gra3.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
    attributes: [
      { key: "Rodzaj gry", value: "Sportowa" },
      { key: "Platforma", value: "PC" },
    ],
  },
  {
    name: "LEGO Star Wars: Przebudzenie Mocy Gra XBOX ONE (Kompatybilna z Xbox Series X)",
    description:
      " Gatunek: Akcja, Przygodowa Nośnik: Blu-ray Wersja językowa: Polska (dubbing) Platforma: Xbox One, Xbox Series X Rodzaj: Gra",
    count: 25,
    price: 500,
    category: "Gry",
    images: [
      { path: "/img/front/gra4.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
    attributes: [
      { key: "Rodzaj gry", value: "Przygodowa" },
      { key: "Platforma", value: "Xbox One" },
    ],
  },
  {
    name: "Fotel uszak wypoczynkowy do salonu FOAL",
    description:
      "Cały mebel obszyty delikatnym i miłym w dotyku materiałem z ozdobnym pikowaniem typu caro osadzony jest na smukłych, ciekawie wyprofilowanych nóżkach. Wybierając fotel do salonu powinniśmy kierować się przede wszystkim wygodą oraz tym, aby dopasował się do całego wnętrza. Taki jest właśnie nasz najnowszy fotel typu „uszak” - szerokie siedzisko zapewnia ogromny komfort a dzięki swej unikatowości stanie się ozdobą każdego pomieszczenia .",
    count: 50,
    price: 1379,
    category: "Meble",
    images: [
      { path: "/img/foletuszak.jpg" },
      { path: "/img/front/monitors.jpg" },
      { path: "/img/front/tablets.jpg" },
    ],
    rating: 5,
    reviewsNumber: 8,
    reviews: [],
    attributes: [
      { key: "Fotele", value: "Fotele uszaki" },
    ],
  },
]

module.exports = ProductSeeder